openapi: 3.0.0
info:
  title: Biblioteca API
  description: Sistema simple de operaciones crud con libros
  version: 0.1.9
servers:
  - url: http://localhost:8080/api/v1
    description: Servidor local 
paths:
  /libros:
    get:
      summary: Returns a list of libros.
      description: Devuelve una lista de libros
      responses:
        '200':    # status code
          description: Un arreglo json de objetos libro.
          content:
            application/json:
              schema: 
                type: array
                items: 
                  $ref: '#/components/schemas/Libro'
    post:
      summary: Devuelve el libro recien creado con su id.
      description:  Devuelve el libro recien creado con su id.
      responses:
        '201':    # status code
          description: Un arreglo json de objetos libro.
          content:
            application/json:
              schema: 
                type: array
                items: 
                  $ref: '#/components/schemas/Libro'
        '400':
          description: Error del cliente, objeto mal formado o validación no cumplida.
  /put/{id}:
    put:
      summary: Actualiza un libro proporcionando su id
      description: Actualiza un libro
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: number
      responses:
        '201':
          description: Devuelve el libro actualizado
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Libro'
        '404':
          description: Libro no encontrado
  /delete/{id}:
    delete:
      summary: Borra el libro proporcionado en el id
      description: Borra el libro proporcionado en el id
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: number
      responses:
        '204':
          description: Libro borrado con éxito
        '404':
          description: Libro no encontrado
      
  /libros{id}:
    get:
      summary: Devuelve el libro por su id
      description: Devuelve el libro por su id
      parameters:
        - in : path
          required: true
          name: id
          schema:
            type: number
      responses:
        '200':
          description: Devuelve el libro con el id especificado
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Libro'
        '404':
          description: Libro no encontrado
components:
    schemas:
      Libro:
        type: object
        properties:
          id:
            type: number
          titulo:
            type: string
          editorial:
            type: string
          tema:
            type: string
          autores:
            type: array
            items:
              $ref: '#/components/schemas/Autor'
      
      Autor:
        type: object
        properties:
          id: 
            type: number
          apellido:
            type: string
          nombre:
            type: string
